interface IEffect {
  Source: string
  vigor: number
  mind: number
  endurance: number
  strength: number
  dexterity: number
  intelligence: number
  faith: number
  arcane: number
  hpRate: number
  mpRate: number
  stamRate: number
  weightRate: number
  physCutRate: number
  strikeCutRate: number
  slashCutRate: number
  pierceCutRate: number
  magCutRate: number
  fireCutRate: number
  lightningCutRate: number
  holyCutRate: number
  physCutRateMP: number
  strikeCutRateMP: number
  slashCutRateMP: number
  pierceCutRateMP: number
  magCutRateMP: number
  fireCutRateMP: number
  lightningCutRateMP: number
  holyCutRateMP: number
  fullHpCutRate: number
  criticalHpCutRate: number
  immunityAddRate: number
  robustnessAddRate: number
  focusAddRate: number
  vitalityAddRate: number
  itemDiscovery: number
  Effects: string
}